// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaQNonEo30D0LXrR5L2VrmDazizhRrjik',
    appId: '1:450369290921:web:af5352510708865ed9dfb8',
    messagingSenderId: '450369290921',
    projectId: 'veo-veo-9d124',
    authDomain: 'veo-veo-9d124.firebaseapp.com',
    storageBucket: 'veo-veo-9d124.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBka18PUTJCzYlBUTJroI5-diTepkzo66A',
    appId: '1:450369290921:ios:c76770a383ba7421d9dfb8',
    messagingSenderId: '450369290921',
    projectId: 'veo-veo-9d124',
    storageBucket: 'veo-veo-9d124.appspot.com',
    iosBundleId: 'com.example.veoVeo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBka18PUTJCzYlBUTJroI5-diTepkzo66A',
    appId: '1:450369290921:ios:c76770a383ba7421d9dfb8',
    messagingSenderId: '450369290921',
    projectId: 'veo-veo-9d124',
    storageBucket: 'veo-veo-9d124.appspot.com',
    iosBundleId: 'com.example.veoVeo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaQNonEo30D0LXrR5L2VrmDazizhRrjik',
    appId: '1:450369290921:web:3cfa79d41e58fa30d9dfb8',
    messagingSenderId: '450369290921',
    projectId: 'veo-veo-9d124',
    authDomain: 'veo-veo-9d124.firebaseapp.com',
    storageBucket: 'veo-veo-9d124.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJuTKUje11_IMnz44KAr855w9xXUb0t0M',
    appId: '1:450369290921:android:d1d2923f8a5067d0d9dfb8',
    messagingSenderId: '450369290921',
    projectId: 'veo-veo-9d124',
    storageBucket: 'veo-veo-9d124.appspot.com',
  );

}